# Generated by Django 3.2.4 on 2021-08-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picblog', '0007_remove_post_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
